### ISSUE TITLE
Doc/Deployment

### ISSUE THREAD

**Issue by dpalmeira** [camptocamp/helm-geoserver-cloud#13]
Hi!, I've found today this excellent repo, and first of all, thank you for your work and passion!
I just also installed it in my local machine by following your readme instructions, and it works. (I had problems with Minikube, but it works well with k3d for me).

Context:
I need to deploy a GeoServer in GKE to serve custom WFS layers stored in a PostGIS db that I want to deploy in GKE also.

0) Do you have some documentation about how to use this Helm in real PROD env?

1) I've noticed you already have a PostgreSQL, what is it used for? Should I create another Postgres to enable it as PostGIS and put my custom data there, or do I have to use the same PostgreSQL (enabling Geospatial) as you are providing here in order to save resources?

2) What are the PVs that should I have to add to make the data permanent in my PROD env? I guess that you have at least one PV for the Postgresql, and may another PV for Geoserver or RabbitMQ?

3) Some advice from you about the PROD security that I have to consider to use your helm project correctly? 

Thank you for your answers.

**Comment by danduk82** [comment]
hello @dpalmeira (sorry I didn't notice your issue earlier),

first of all, if you need help for your integration in GKE, don't hesitate to contact us ([info@camptocamp.com](mailto:info@camptocamp.com)) for a support contract and we will be able to help you directly.

The postgresql server in the chart uses a non persistent volume and is rated for dev only. It is used for the storage of the geoserver configuration using the JDBC connector. You must set `.Values.geoserver.jdbc.external=true` to use an external pg database for that. ( and set `.Values.postgresql.enable=false).

RabbitMQ uses the bitnami chart, so you can configure it as you want.

For the geodata, you need a dedicated store (say a dedicated postgis database for vector data). In the chart there is also the possiblity to add a reference to a NFS PVC and mount it directly in the pods in the `volumeMount` of your choice.

Btw, this chart is not for geoserver, but for [geoserver-cloud](https://github.com/geoserver/geoserver-cloud) (spring boot application based on geoserver).

Sincerely
