### ISSUE TITLE
Upgrade to gscloud 1.7.1 / acl 2.1.1

### ISSUE THREAD

**Issue by groldan** [camptocamp/helm-geoserver-cloud#198]
Upgrade the chart to use gscloud version `1.7.1` and ACL version `2.1.0`

## geoserver-cloud 1.7.1
* As requested, the gateway routes the acl service to `${geoserver.base-path}/acl` instead of `/acl`

## ACL 2.1.1

* ACL actuator port is `8081`, but path changes from `/acl/actuator` to `/actuator`. Update liveness/readiness
* Fixes the swagger ui to work behind a reverse proxy

**Comment by jemacchi** [comment]
Attached the related branch.
