### ISSUE TITLE
WPS

### ISSUE THREAD

**Issue by sgavathe** [camptocamp/helm-geoserver-cloud#58]
Thank you for putting the helm chart together. It's awesome.

I don't see WPS service anywhere , when it's loaded. How do you configure or enable it in the chart?

**Comment by danduk82** [comment]
Hello @sgavathe , the WPS module is not yet part of the gs-cloud. If you might a need of the WPS module , please consider contributing to [gs-cloud codebase](https://github.com/geoserver/geoserver-cloud)

**Comment by sgavathe** [comment]
Ahh got you @danduk82 . So WPS is not part of the main geoserver-cloud. I know it needs a file based system for WPS to store , process and run. And the current chart is purely jdbcConfig via RDS or the provided postgres instance. Will check into how that can be done. And I am assuming that's why there is no log system in the chart either. 

And we also noticed that Geoserver Web Page is painfully slow when used RDS. It takes about 30 seconds to navigate to a different menu of the page. Is there any tips on how to improve that. 

Thanks @danduk82

**Comment by danduk82** [comment]
Jdbcconfig in general is pretty sluggish also in vanilla geoserver afaik. You can actually use the [ `datadir` profile](https://github.com/danduk82/helm-ogscloud/blob/master/values.yaml#L24) and use a block RWX storageClass. I use a [NFS server for the datadir](https://github.com/danduk82/helm-ogscloud/blob/master/values.yaml#L105-L107) in my playground deployment. Any RWX storageClass would work, just use what you have available in your k8s cluster.

If you need some help to setup gs-cloud in your AWS account, please consider contacting us ([info@camptocamp.com](mailto:info@camptocamp.com)) for a support contract and I will be able to help you directly.

**Comment by danduk82** [comment]
closing this stale issue
