### ISSUE TITLE
Project setup fails into Kubernetes

### ISSUE THREAD

**Issue by giancastro** [camptocamp/helm-geoserver-cloud#67]
To setup into Kubernetes, I ran the following commands:
```
helm dependency update
helm install geoserver .
```

<img width="717" alt="Screen Shot 2022-06-15 at 13 04 04" src="https://user-images.githubusercontent.com/16704806/173874233-fe01328e-4693-468a-be66-dbb44df0b7ef.png">

**Comment by danduk82** [comment]
Hello @giancastro , 
the README is meant to work with a local K3D instance as K8S. If that is not your case, you must adapt your URL and ingress to your setup.
To debug why the pods are in `CrashLoopBackOff`status, you should use `kubectl` and use the `describe pod` subcommand, and/or `logs` subcommand to get more insights.

**Comment by ubiseli** [comment]
@giancastro, any luck figuring this one out? Mind sharing? :) I'm currently stuck at CrashLoopBackOff as well.

**Comment by giancastro** [comment]
@ubiseli I wasn't able to figure it out. I set it up manually instead of using the helm.
